name: stacked_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stacked: ^2.3.15+1
  stacked_services: ^0.9.5
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  stacked_firebase_auth: ^0.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.7.15
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Semibold.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
